[package]
name = "phizone-player"
version = "0.1.3"
description = "An HTML5 Phigros chart player/simulator based on Phaser"
authors = ["PhiZone"]
license = "MPL-2.0"
repository = "https://github.com/PhiZone/player"
edition = "2021"
rust-version = "1.71"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2", features = [] }
tauri-plugin-log = "2"
tauri-plugin-deep-link = "2"
tauri-plugin-os = "2"
tauri-plugin-upload = "2"
tauri-plugin-fs = "2"
url = "2"
image = "0.25.5"
chrono = "0.4.40"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = { version = "2.0.0", features = ["deep-link"] }
