name: Build Android
run-name: Build for Android
on:
  push:
    branches:
      - defres
  pull_request:
    branches:
      - defres
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: defres

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm i

      - name: Create build
        run: pnpm build && pnpm cap update

      - name: Generate icons and splash screen
        run: if [ -d "./resources" ]; then pnpm i -D @capacitor/assets && pnpm capacitor-assets generate --android; fi

      - name: Build app bundle
        run: cd android && chmod +x ./gradlew && ./gradlew bundle && ./gradlew assembleDebug

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks

      - name: Sign dev build
        run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      - name: Check folder content of Android output
        run: ls ./android/app/build/outputs/bundle/release

      - name: Specify version
        id: version
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Specify current time
        id: current-datetime
        run: |
          echo "CURRENT_DATETIME=$(date +'%m%d-%H%M')" >> "$GITHUB_OUTPUT" && \
          echo "CURRENT_DATETIME_FULL=$(date +'%Y-%m-%d %H:%M:%S (%z)')" >> "$GITHUB_OUTPUT"

      - name: Build release
        run: |
          gh release create "v${{ steps.version.outputs.VERSION }}" \
          --title "v${{ steps.version.outputs.VERSION }} ${{ steps.current-datetime.outputs.CURRENT_DATETIME }}" \
          --notes "Automated build at ${{ steps.current-datetime.outputs.CURRENT_DATETIME_FULL }}" \
          ./android/app/build/outputs/bundle/release/app-release-signed.aab \
          ./android/app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
